apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
  labels:
    appType: web
spec:
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: server
          image: forcad-service
          env:
            - name: SERVICE
              value: "monitoring"
          readinessProbe:
            httpGet:
              path: /api/metrics/health/
          livenessProbe:
            httpGet:
              path: /api/metrics/health/

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring
spec:
  type: ClusterIP
  selector:
    app: monitoring
  ports:
    - name: http
      port: 5000
      targetPort: 5000
