admin:
  password: d68534a816ca1b10
  username: forcad
game:
  checkers_path: /checkers/
  default_score: 2500.0
  env_path: ''
  flag_lifetime: 5
  game_hardness: 10.0
  inflation: true
  mode: classic
  round_time: 20
  start_time: 2025-01-03 10:46:00
  timezone: Europe/Rome
storages:
  db:
    dbname: forcad
    host: postgres
    password: d68534a816ca1b10
    port: 5432
    user: forcad
  rabbitmq:
    host: rabbitmq
    password: d68534a816ca1b10
    port: 5672
    user: forcad
    vhost: forcad
  redis:
    db: 0
    host: redis
    password: d68534a816ca1b10
    port: 6379
tasks:
- checker: service1/checker.py
  checker_timeout: 10
  checker_type: hackerdom
  gets: 2
  name: Notes
  places: 5
  puts: 2
- checker: service2/checker.py
  checker_timeout: 10
  checker_type: hackerdom
  gets: 2
  name: Polls
  places: 5
  puts: 2
- checker: service3/checker.py
  checker_timeout: 10
  checker_type: hackerdom
  gets: 2
  name: NFB
  places: 5
  puts: 2
teams:
- highlighted: false
  ip: 192.168.1.2
  name: Team 1
- highlighted: true
  ip: 192.168.1.3
  name: Team 2 (highlighted)
